language: node_js
before_script:
- ./scripts/prebuild.sh
node_js:
- 6
sudo: false
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - GH_REPO="AHost4All/AHost4All"
# GH_TOKEN is set in travis's web ui now, username & email are set in scripts/deploy.sh
